enableMessageNames: true

nodeLinker: node-modules

# Fixes issue with eslint plugin conflicts between root config and package configs
pnpFallbackMode: all

# plugins:
#   - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
#     spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-berry.cjs
