name: 'Analyze Pull Request'
on:
  pull_request:
    types: [opened, reopened, synchronize]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  analyze_changes:
    name: Analyze Changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check dependencies
        uses: juanigalan91/monorepolyser@0.2.6
        with:
          check-dependencies: true
          include-main-package-json: true
          impact-analysis: true
          on-high-impact: 'comment,add-labels'
          high-impact-labels: 'high-impact'

      - name: Execute tests
        continue-on-error: true
        working-directory: ./packages/gaia
        run: yarn run jest:ci

      - name: Process test results
        if: always()
        uses: im-open/process-jest-test-results@v2.0.5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          results-file: 'jest-results.json'
          report-name: 'Test Results'
          create-status-check: true
          create-pr-comment: true
          update-comment-if-one-exists: true
