name: 'Analyze Pull Request'
on:
  pull_request:
    types: [opened, reopened, synchronize]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  analyze_changes:
    name: Analyze Changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: fnm

      - name: Setup Node.js
        uses: actions/setup-node@master
        with:
          node-version: '${{ steps.fnm.outputs.NVMRC }}'

      - uses: c-hive/gha-yarn-cache@v2

      - name: Install Dependencies
        run: yarn
        env:
          NPM_TOKEN: '${{ secrets.NPM_TOKEN }}'

      - name: Check dependencies
        uses: juanigalan91/monorepolyser@0.2.6
        with:
          check-dependencies: true
          include-main-package-json: true
          impact-analysis: true
          on-high-impact: 'comment,add-labels'
          high-impact-labels: 'high-impact'

      - name: Execute tests
        continue-on-error: true
        # working-directory: ./packages/gaia
        run: yarn workspace @trubittech/gaia run test:ci

      - name: Log PWD
        run: pwd

      - name: Log contents of current dir
        run: ls -la

      - name: Process test results
        if: always()
        uses: im-open/process-jest-test-results@v2.0.5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          results-file: './packages/gaia/test-results.json'
          report-name: 'Test Results'
          create-status-check: true
          create-pr-comment: true
          update-comment-if-one-exists: true
