name: 'Decorate Pull Request'
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  label_pr:
    name: Add Labels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v2
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
