name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: fnm
      - name: Setup Node.js
        uses: actions/setup-node@master
        with:
          node-version: '${{ steps.fnm.outputs.NVMRC }}'
      - name: Install Dependencies
        run: yarn
        env:
          NPM_TOKEN: '${{ secrets.NPM_TOKEN }}'
      - name: Create Release Pull Request or Publish
        uses: changesets/action@v1
        with:
          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
