name: 'Pull Request'
on:
  pull_request:
    types: [opened, reopened, synchronize]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  label_pr:
    name: Label PR
    runs-on: ubuntu-latest
    steps:
      - name: add package labels
        uses: tinkurlab/monorepo-pr-labeler-action@3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_DIRS: 'packages'
        with:
          prefix: 'pkg:'

  analyze_changes:
    name: Analyze Changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check dependencies
        uses: juanigalan91/monorepolyser@0.2.6
        with:
          check-dependencies: true
          include-main-package-json: true
          impact-analysis: true
          on-high-impact: 'comment,add-labels'
          high-impact-labels: 'high-impact'
